on:
  schedule:
    - cron: "0 0 * * *" # run depsbot everyday at 00:00 UTC
jobs:
  depsbot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Run depsbot
        uses: denosaurs/depsbot@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

